//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items_x_Factura
    {
        public int Id { get; set; }
        public int Factura { get; set; }
        public int Item { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual Items Items { get; set; }
    }
}
